### ISSUE TITLE
Django-cms show_menu error: 'function' object has no attribute 'compile'

### ISSUE THREAD

**Issue by source3** [divio/django-cms#5267]
This is a duplicate of my stackoverflow post at http://stackoverflow.com/questions/37126040

I am in the process of upgrading a Django-CMS project one release at time.  Everything is working on Django 1.6.11/Django-CMS 3.0.15 (running Python 2.7.11 in a virtualenv on Ubuntu).  I upgraded another project without this error.

When upgrading to Django 1.7.1/Django-CMS 3.0.15 the show_menu tag throws an error. `show_breadcrumb` also throws the same error.  I can remove the `show_menu` tag and the pages render correctly.  I have `load menu_tags` before `show_menu` in `base.html`.

The error in debug mode gives

     Exception Value: 'function' object has no attribute 'compile'
     Exception Location:	/ebs/dcenvironmental/lib/python2.7/site-packages/django/db/models/sql/where.py in as_sql, line 106

I also tested using a new blank database and created a new page.  Still had the same error.

I have no idea what is causing this error.  Any help is much appreciated.

**Comment by czpython** [comment]
@source3 Hello, thanks for reporting. Could you provide us with a full traceback?

**Comment by source3** [comment]
Here you go.

Environment:


Request Method: GET
Request URL: http://base.source3.com:8000/en/

Django Version: 1.7.11
Python Version: 2.7.11
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'djangocms_text_ckeditor',
 'cms',
 'treebeard',
 'mptt',
 'menus',
 'sekizai',
 'djangocms_admin_style',
 'django.contrib.admin',
 'django.contrib.sites',
 'easy_thumbnails',
 'ganalytics',
 'menu_external_urls',
 'filer',
 'cmsplugin_filer_file',
 'cmsplugin_filer_folder',
 'cmsplugin_filer_image',
 'cmsplugin_filer_teaser',
 'cmsplugin_filer_video',
 'cmsplugin_filer_link',
 'djangocms_flash',
 'djangocms_googlemap',
 'djangocms_link',
 'cmsplugin_biography',
 'export_xls',
 'paypal.standard.ipn',
 'form_designer',
 'form_designer.contrib.cms_plugins.form_designer_form',
 'calendarapp',
 'django_comments',
 'tagging',
 'zinnia',
 'cmsplugin_zinnia',
 'slideshows',
 'filebrowser',
 'smart_load_tag')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.doc.XViewMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware',
 'cms.middleware.language.LanguageCookieMiddleware')


Template error:
In template /ebs/dcenvironmental/dcenvironmental/templates/base.html, error at line 48
   'function' object has no attribute 'compile'
   38 :         <a class="webicon linkedin" target="_blank" href="http://www.linkedin.com/company/dc-environmental-inc-?trk=top_nav_home">LinkedIn</a>


   39 :       </div>


   40 :     </div>


   41 :     


   42 : 


   43 :     


   44 :     


   45 :     


   46 :     


   47 :     <div class="row">


   48 :       <div class="small-12"> {% show_menu 0 1 10 10 "my_menu/menu-custom.html" %} </div>


   49 :     </div>


   50 :         


   51 :    


   52 :        


   53 :        


   54 :     {% block base_content %}


   55 : 


   56 :     {% endblock base_content %}


   57 :     


   58 :     


Traceback:
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  137.                 response = response.render()
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/response.py" in render
  103.             self.content = self.rendered_content
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/response.py" in rendered_content
  80.         content = template.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/base.py" in render
  148.             return self._render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  126.         return compiled_parent._render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/classytags/core.py" in render
  106.         return self.render_tag(context, **kwargs)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/cms/templatetags/cms_tags.py" in render_tag
  666.         rendered_contents = nodelist.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/classytags/core.py" in render
  106.         return self.render_tag(context, **kwargs)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py" in render_tag
  79.         rendered_contents = nodelist.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/classytags/core.py" in render
  106.         return self.render_tag(context, **kwargs)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/classytags/helpers.py" in render_tag
  86.             data = context.new(self.get_context(context, **kwargs))
File "/ebs/dcenvironmental/lib/python2.7/site-packages/menus/templatetags/menu_tags.py" in get_context
  133.             nodes = menu_pool.get_nodes(request, namespace, root_id)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/menus/menu_pool.py" in get_nodes
  256.         nodes = self._build_nodes(request, site_id)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/menus/menu_pool.py" in _build_nodes
  215.                 nodes = menu.get_nodes(request)
File "/ebs/dcenvironmental/lib/python2.7/site-packages/cmsplugin_zinnia/menu.py" in get_nodes
  125.         for tag in tags_published():
File "/ebs/dcenvironmental/lib/python2.7/site-packages/zinnia/managers.py" in tags_published
  20.         Entry.published.all())
File "/ebs/dcenvironmental/lib/python2.7/site-packages/tagging/models.py" in usage_for_queryset
  170.                 compiler.quote_name_unless_alias, compiler.connection
File "/ebs/dcenvironmental/lib/python2.7/site-packages/django/db/models/sql/where.py" in as_sql
  106.                     sql, params = qn.compile(child)

Exception Type: AttributeError at /en/
Exception Value: 'function' object has no attribute 'compile'

**Comment by czpython** [comment]
@source3 Thanks.

This looks like a django-blog-zinnia bug, it was fixed a while back https://github.com/Fantomas42/django-blog-zinnia/issues/375.

Make sure to use latest version, also I'm not sure if it supports Django 1.7 yet (django-tagging fork).

**Comment by source3** [comment]
The issue was the django-tagging version I was using.  I had django-tagging==0.3.1.  Zinnia requires django-tagging>=0.3.6.  Upgrading to 0.3.6 fixed the issue.  

Thank you for all the help and pointing me to look at my requirements with Zinnia and tagging!  I already applied the bug fix for zinnia but forgotten about the error it first caused.
