### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_inc_path' after upgrading to 3.1.4

### ISSUE THREAD

**Issue by Vesli** [divio/django-cms#4894]
Hi and happy new year to everyone !

As recommended recently on stackoverflow, I upgraded to django-cms 3.1.4, ran the cms fix-tree command but...

>Internal Server Error: /en/admin/djangocms_blog/post/add-plugin/
Traceback (most recent call last):
  File
 "/var/www/webapps/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File
 "/var/www/webapps/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File
 "/var/www/webapps/lib/python3.4/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File
 "/var/www/webapps/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File
 "/var/www/webapps/lib/python3.4/site-packages/aldryn_reversion/admin.py", line 32, in add_plugin
    request)
  File
 "/var/www/webapps/lib/python3.4/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File
 "/var/www/webapps/lib/python3.4/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File
 "/var/www/webapps/lib/python3.4/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File
 "/var/www/webapps/lib/python3.4/site-packages/django/views/decorators/clickjacking.py", line 41, in wrapped_view
    resp = view_func(*args, **kwargs)
  File
 "/var/www/webapps/lib/python3.4/site-packages/cms/admin/placeholderadmin.py", line 264, in add_plugin
    plugin.save()
  File
 "/var/www/webapps/lib/python3.4/site-packages/cms/models/pluginmodel.py", line 232, in save
    self.parent.add_child(instance=self)
  File "/var/www/webapps/lib/python3.4/site-packages/treebeard/mp_tree.py",
 line 970, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/var/www/webapps/lib/python3.4/site-packages/treebeard/mp_tree.py",
 line 359, in process
    newobj.path = self.node.get_last_child()._inc_path()
AttributeError: 'NoneType' object has no attribute '_inc_path'

This is what I got when I try to add a new blog post or, in a general way, when I try to use a CMS Plugins inside CK-Editor.
All of it with a pretty pop-up :
>There was an error creating the plugin.

:(

**Comment by czpython** [comment]
@Vesli hello. Did the fix-tree command finish successfully?

**Comment by Vesli** [comment]
Hi @czpython !

yes, here is the report :

>(webapps)admin@ip-10-31-2-94:/var/www/webapps/website/app$ ./manage.py cms fix-tree
fixing page tree
fixing plugin tree
all done

**Comment by czpython** [comment]
Can you try a new page?

So create a cms page, add a plugin to a placeholder and then add a child plugin to the first plugin.

**Comment by Vesli** [comment]
Well, the test you ask me as always worked. Or maybe I don't get it ;

But I did it :
create an empty page with one PH, created a Multi Columns plugin -> column -> text plugin

<img width="1419" alt="screen shot 2016-01-07 at 13 32 19" src="https://cloud.githubusercontent.com/assets/10052941/12171603/25171740-b543-11e5-9bf6-084152371139.png">

**Comment by czpython** [comment]
Cool, thanks for the screenshot. Makes things easier.
Can you post one for the page where it fails?

The test has isolated the problem to only one page.

**Comment by Vesli** [comment]
You're welcome.

ok then, step by step :

I click on a text plugin

<img width="699" alt="screen shot 2016-01-07 at 13 45 58" src="https://cloud.githubusercontent.com/assets/10052941/12171904/51a64e8c-b545-11e5-953c-eae5d6540d9a.png">

I add a cms plugin :

<img width="477" alt="screen shot 2016-01-07 at 13 47 13" src="https://cloud.githubusercontent.com/assets/10052941/12171908/5d7b39d4-b545-11e5-97fe-5f782270d459.png">

and the error from my first post appears :

<img width="594" alt="screen shot 2016-01-07 at 13 47 27" src="https://cloud.githubusercontent.com/assets/10052941/12171912/661d1314-b545-11e5-8fa2-5a4ea1e51461.png">

you have the backend detail on my first post.

thank you very much for your concern !

**Comment by czpython** [comment]
@Vesli I'm not very familiar with djangocms-blog.

How is that text plugin created?
Did you create it manually by just creating an article and then adding the text plugin to the article placeholder?

Basically the problem is that your text plugin internally is marked as having children so when you add the twitter plugin it tries to get the text plugin last child and add the twitter plugin after it but because there's no "last child" since the text plugin has no children prior to the twitter plugin then it fails.
So I'm trying to determine what causes the CMS to mark the text plugin as having children.

**Comment by Vesli** [comment]
It's not with djangocms-blog, my apologies, it happens with every placeholder text when I want to add one of the CMS Plugins.

**Comment by czpython** [comment]
@Vesli aha so basically you create a page, add a text plugin and then while editing text try to add another plugin and it doesn't work?

If this is the case please specify the ckeditor version also just in case the django version.

**Comment by Vesli** [comment]
Hmm I feel like I am about to be the silly one haha.
Here are the versions :
djangocms-text-ckeditor==2.4.3
Django==1.7.10

**Comment by czpython** [comment]
@Vesli please upgrade to the latest 2.7 release of ckeditor, in this case it's djangocms-text-ckeditor==2.7.1

**Comment by Vesli** [comment]
youhou it works !

Well I was the silly one, thank you so much for your time spent on simply opening my eyes...

You have my gratitude. And my apologies !!

**Comment by czpython** [comment]
@Vesli Awesome. Glad it works :)

About the blog, if you can please open a ticket on the djangocms-blog repo with traceback/steps/etc.
