### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by macalicious** [divio/django-cms#4633]
Will django-cms get support for `Python 3.5` anytime soon?
Right now trying to install throws an `AttributeError: module 'html.parser' has no attribute 'HTMLParseError'` exception, since that module has been deprecated since `Python 3.3`, but been dropped completely with `Python 3.5` now.

**Comment by cimocimocimo** [comment]
Django 1.8 doesn't currently support Python 3.5. Django 1.9 will however.

https://docs.djangoproject.com/en/dev/releases/1.9/

**Comment by yakky** [comment]
@cimocimocimo Django 1.8 works on python 3.5 (albeit is not officially supported). any lower version doesn't.
django CMS itself is compatible with 3.5
